/* The Mini — curated crossword clues.

   The generator's default clues come from dictionary definitions (bundled
   lists, or a Datamuse harvest). Those are accurate but read like a glossary:
   "Strong wind", "Spoken", "Card type". Real crossword clues misdirect, use
   fill-in-the-blank, lean on proper nouns and idiom, and vary in register.

   This file overrides the definition for answers that show up often, which is
   where the difference is felt most — the crosswordese that would otherwise
   be clued most blandly. Anything not listed here still falls back to the
   dictionary definition, so partial coverage degrades gracefully.

   Format: ANSWER: [clue, clue, ...], ordered EASIEST FIRST, HARDEST LAST.
   generator.js's pickClueByDifficulty() weights which end of this array a
   puzzle draws from — Very Easy draws from the front, Impossible from the
   back, Medium roughly uniformly — so the ordering isn't just cosmetic. Put
   a plain, direct definition first; save fill-in-the-blank, wordplay, and
   indirect phrasing ("___ before the storm") for the end. Keep them short —
   the clue bar is one line on mobile. */
(function (global) {
  'use strict';

  global.CURATED_CLUES = {
    /* ---- the classic crosswordese ---- */
    OREO: ['Cookie that\'s often twisted', 'Sandwich in a lunchbox', 'Double Stuf snack'],
    AREA: ['Length times width', 'Neighborhood', 'Rug spec'],
    ERIE: ['Great Lake bordering Ohio', 'Canal of song', 'Pennsylvania port city'],
    IDEA: ['Lightbulb moment', 'Brainstorm result', 'What a bulb signifies'],
    ALOE: ['Sunburn soother', 'Vera\'s plant?', 'Gel-yielding succulent'],
    IRON: ['Golf club or laundry tool', 'Pumping ___', 'Element 26'],
    ECHO: ['Canyon comeback', 'Smart speaker name', 'Repeat offender?'],
    OPEN: ['Not shut', 'Tennis tournament type', 'Ready for business'],
    EASE: ['Lack of difficulty', 'Relieve', 'Put at ___'],
    ERAS: ['Taylor Swift tour name', 'Jurassic and Victorian, e.g.', 'Long stretches'],

    /* ---- three letters ---- */
    ACE: ['Nail the test', 'Top card', 'Serve that can\'t be returned'],
    ADD: ['Do some sums', 'Toss in', 'Opposite of subtract'],
    AGE: ['Get older', 'Number on a cake', 'Bronze or Ice, e.g.'],
    AIR: ['What a tire loses', 'Broadcast', 'Guitar prefix?'],
    ANT: ['Picnic pest', 'Colony member', 'Marvel\'s ___-Man'],
    APE: ['Copy', 'Kong, for one', 'Go ___ (freak out)'],
    ARM: ['Limb with an elbow', 'Chair part', 'Supply with weapons'],
    ART: ['Museum filler', 'The ___ of the Deal', 'Gallery display'],
    ATE: ['Had a bite', 'Consumed', 'Was fed up?'],
    BAT: ['Cave dweller', 'Slugger\'s stick', 'Take a turn at the plate'],
    BEE: ['Spelling contest', 'Hive dweller', 'Busy as a ___'],
    BOX: ['Ring contest', 'Cardboard container', 'Think outside the ___'],
    CAT: ['Nine-lived pet', 'Curiosity victim', 'Jazz fan, once'],
    COW: ['Milk source', 'Have a ___ (freak out)', 'Intimidate'],
    DOG: ['Best friend, they say', 'Hot ___', 'Follow closely'],
    EAR: ['Corn unit', 'It has a drum', 'Lend an ___'],
    EGG: ['Breakfast staple', 'Nest item', '___ on (encourage)'],
    END: ['Finish', 'Football position', 'Means to an ___'],
    EYE: ['Storm center', 'Needle hole', 'Keep an ___ on'],
    FAN: ['Cooling device', 'Devotee', 'Stadium filler'],
    FIT: ['Tantrum', 'In shape', 'Suitable'],
    FLY: ['Soup intruder', 'Travel by air', 'Zipper, on trousers'],
    ICE: ['Rink surface', 'Cubes in a glass', 'Seal the deal, slangily'],
    INK: ['Pen filler', 'Tattoo, informally', 'Sign a deal'],
    JAM: ['Toast topping', 'Traffic snarl', 'Play music loosely'],
    KEY: ['Piano part', 'It opens doors', 'Florida ___ lime'],
    LAP: ['Track circuit', 'Sit on Santa\'s ___', 'Drink like a cat'],
    NET: ['Tennis divider', 'After deductions', 'Catch'],
    OAR: ['Rowboat mover', 'Crew tool', 'Put your ___ in'],
    OWL: ['Night bird', 'Wise one, proverbially', 'Hooter'],
    PEN: ['Writing tool', 'Pig\'s home', 'Mightier than the sword'],
    PIE: ['Bakery buy', 'Chart type', 'Easy as ___'],
    RAT: ['Squealer', 'Lab animal', 'Smell a ___'],
    RUN: ['Jog', 'Stocking flaw', 'Baseball score'],
    SEA: ['Ocean', 'All at ___ (confused)', 'Dead or Red'],
    SKY: ['The limit, they say', 'Blue expanse', 'Where clouds live'],
    SUN: ['Star of our system', 'Beach draw', 'It rises in the east'],
    TEA: ['Cuppa', 'Boston Harbor cargo, once', 'Spill the ___ (gossip)'],
    TIE: ['Neckwear', 'Deadlocked score', 'Bind'],
    TOE: ['Foot digit', '___ the line', 'Sock coverer'],
    TOP: ['Spinning toy', 'Best', 'Shirt, e.g.'],
    WEB: ['Spider\'s work', 'The World Wide ___', 'Network'],
    ZIP: ['Nothing at all', 'Code before an address', 'Fastener'],

    /* ---- four letters ---- */
    ABLE: ['Capable', 'Ready, willing, and ___', 'Cain\'s brother, nearly'],
    ACHE: ['Dull pain', 'Long (for)', 'Head or heart follower'],
    ACID: ['Base opposite', 'Battery liquid', 'Sharp, as wit'],
    ALSO: ['Too', 'In addition', 'Besides'],
    ATOM: ['Tiny bit', 'Splittable thing', 'Element unit'],
    AUTO: ['Car', 'Prefix with pilot', 'Detroit product'],
    BAKE: ['Use the oven', 'Half-___ idea', 'Make cookies'],
    BEAM: ['Grin widely', 'Structural support', 'Ray of light'],
    BELL: ['Ringer', 'Taco ___', 'Saved by the ___'],
    BIRD: ['Early one gets the worm', 'Badminton shuttlecock', 'Larry of the Celtics'],
    BLUE: ['Feeling down', 'Sky color', 'Out of the ___'],
    BOLD: ['Daring', 'Text style', 'Fortune favors the ___'],
    CALM: ['Serene', '___ before the storm', 'Settle down'],
    CARD: ['Deck member', 'Birthday mailing', 'Funny person'],
    CHIP: ['Poker token', 'Salsa scooper', '___ on one\'s shoulder'],
    CITY: ['Urban area', 'Kansas ___', 'Metropolis'],
    COLD: ['Winter feeling', 'Sniffles cause', 'Out ___ (unconscious)'],
    DEAL: ['Bargain', 'Distribute cards', 'Big ___!'],
    DESK: ['Office furniture', 'Where papers pile up', 'Front ___ clerk'],
    DOOR: ['Entryway', 'Next ___ neighbor', 'It may be revolving'],
    EDGE: ['Border', 'Slight advantage', 'On ___ (nervous)'],
    FACE: ['Clock front', 'Confront', 'Poker ___'],
    FIRE: ['Campfire', 'Let go from a job', 'Under ___'],
    FISH: ['Angler\'s catch', 'Aquarium resident', 'Search awkwardly'],
    GAME: ['Match', 'Willing', 'Board or video'],
    GATE: ['Airport waiting spot', 'Fence opening', 'Golden ___ Bridge'],
    GOLD: ['Olympic prize', 'Element 79', 'Heart of ___'],
    HAND: ['Cards you\'re dealt', 'Clock pointer', 'Give a ___'],
    HOME: ['Where the heart is', 'Baseball plate', 'House'],
    IDLE: ['Doing nothing', 'Monty Python\'s Eric', 'Engine state'],
    JAZZ: ['New Orleans music', 'Utah team', 'Liven (up)'],
    KING: ['Chess piece', 'Elvis, with "the"', 'Martin Luther ___ Jr.'],
    LAKE: ['Erie or Tahoe', 'Body of water', 'Salt ___ City'],
    LEAF: ['Autumn faller', 'Book page', 'Turn over a new ___'],
    LINE: ['Queue', 'Drop me a ___', 'Fishing cord'],
    MOON: ['Night light', 'Over the ___', 'Apollo destination'],
    NOTE: ['Musical unit', 'Brief message', 'Take ___ of'],
    PARK: ['Leave the car', 'Ball ___', 'Central ___'],
    RAIN: ['Umbrella opener', '___ check', 'Wet weather'],
    RIDE: ['Amusement park attraction', 'Lift', 'Along for the ___'],
    ROAD: ['Highway', 'Hit the ___', 'Abbey ___'],
    ROCK: ['Genre of music', 'Stone', 'Sway back and forth'],
    SALT: ['Pepper\'s partner', 'Sea seasoning', 'Worth one\'s ___'],
    SNOW: ['Winter white stuff', 'Jon of Winterfell', 'Blizzard output'],
    STAR: ['Celebrity', 'Twinkler', 'Rate five ___s'],
    TIME: ['Clock reading', 'Magazine name', '___ flies'],
    WAVE: ['Ocean roller', 'Greeting gesture', 'Stadium crowd move'],
    WIND: ['Breeze', 'Coil up', 'Second ___'],
    WOOD: ['Fireplace fuel', 'Golf club type', 'Can\'t see the forest for the ___s'],

    /* ---- five letters ---- */
    ADAPT: ['Adjust', 'Turn a book into a film', 'Evolve to fit'],
    ADMIT: ['Confess', 'Let in', 'Own up'],
    ALERT: ['On guard', 'Amber ___', 'Warning'],
    ALIVE: ['Kicking', 'Not dead', 'Look ___!'],
    ANGEL: ['Winged helper', 'Investor in a startup', 'Los ___es'],
    APPLE: ['Teacher\'s gift', 'Big ___ (NYC)', 'Newton\'s falling fruit'],
    BEACH: ['Sandy shore', 'Boys of song', 'Where waves land'],
    BEGIN: ['Start', 'Commence', 'Opposite of end'],
    BRAVE: ['Courageous', 'Atlanta ballplayer', 'Face down'],
    BREAD: ['Loaf', 'Money, slangily', 'Bakery staple'],
    BRIEF: ['Short', 'Lawyer\'s filing', 'Fill in quickly'],
    CHAIR: ['Seat', 'Committee head', 'Musical ___s'],
    CLEAN: ['Spotless', 'Come ___ (confess)', 'Tidy up'],
    CLOUD: ['Sky puffball', 'Where data lives now', 'On ___ nine'],
    DANCE: ['Move to music', 'Prom activity', 'Last ___'],
    DREAM: ['Sleep vision', 'Aspiration', 'Field of ___s'],
    EARTH: ['Third rock from the sun', 'Soil', 'Down to ___'],
    ENTER: ['Go in', 'Keyboard key', 'Sign up for'],
    EQUAL: ['The same', 'Sweetener brand', 'All men are created ___'],
    FIELD: ['Baseball setting', 'Area of study', 'Left ___'],
    FLAME: ['Candle top', 'Old ___ (former love)', 'Fire part'],
    FRESH: ['Just picked', 'Sassy', '___ start'],
    FRUIT: ['Apple or pear', 'Labor\'s reward', 'Forbidden ___'],
    GHOST: ['Halloween figure', 'Stop replying, in dating', 'Casper, e.g.'],
    GRAND: ['Impressive', 'Thousand bucks', 'Piano type'],
    GREEN: ['Kermit\'s color', 'Golf target', 'Eco-friendly'],
    HAPPY: ['Glad', 'Dwarf with a grin', '___ hour'],
    HEART: ['Valentine shape', 'Card suit', 'Take it to ___'],
    HOUSE: ['Dwelling', 'Congress chamber', 'Full ___'],
    LAUGH: ['Chuckle', 'Response to a joke', 'Last ___'],
    LEARN: ['Pick up knowledge', 'Study result', 'Live and ___'],
    LEMON: ['Sour citrus', 'Bad car', 'When life gives you ___s'],
    LIGHT: ['Not heavy', 'Bulb output', 'See the ___'],
    LUCKY: ['Fortunate', '___ strike', 'Charm-worthy'],
    MAGIC: ['Sorcery', 'Orlando team', 'Johnson of the Lakers'],
    MONEY: ['Cash', 'Where your mouth is', 'Root of all evil, they say'],
    MUSIC: ['Radio output', 'Notes in sequence', 'Face the ___'],
    NIGHT: ['Day\'s opposite', 'Opening ___', 'Good ___'],
    OCEAN: ['Pacific or Atlantic', 'Frank of R&B', 'Vast blue'],
    PAPER: ['Rock beats it', 'Newspaper', 'Term ___'],
    PARTY: ['Celebration', 'Political group', 'Third ___'],
    PEACE: ['War\'s opposite', 'Nobel category', '___ of mind, nearly'],
    PHONE: ['Pocket device', 'Ring giver', '___ a friend'],
    PIANO: ['88-key instrument', 'Softly, in music', 'Grand or upright'],
    PLANT: ['Factory', 'Put in soil', 'Leafy thing'],
    POWER: ['Electricity', 'Strength', '___ nap'],
    QUICK: ['Fast', 'Cut to the ___', '___ study'],
    RIVER: ['Nile or Amazon', 'Poker\'s last card', 'It has banks'],
    ROBOT: ['Mechanical worker', 'Sci-fi staple', 'Dance style'],
    SHARP: ['Keen', 'Musical symbol', 'At 3 o\'clock ___'],
    SHORE: ['Coastline', 'Jersey ___', 'Prop (up)'],
    SMILE: ['Say cheese', 'Grin', 'Turn that frown around'],
    SNAKE: ['Slithering reptile', 'Plumber\'s tool', 'Treacherous person'],
    SOUND: ['Noise', 'Puget ___', 'Sensible'],
    SPACE: ['Final frontier', 'Room', 'Bar on a keyboard'],
    SPEED: ['Velocity', 'Keanu film', '___ bump'],
    STAGE: ['Theater platform', 'Phase', 'Set the ___'],
    STONE: ['Rock', 'Rolling ___', 'Kidney ___'],
    STORM: ['Bad weather', 'Take by ___', 'Brainstorm, briefly'],
    SUGAR: ['Sweetener', 'Term of endearment', 'Brown or white'],
    SWEET: ['Sugary', 'Home ___ home', 'Kind'],
    TABLE: ['Dining furniture', 'Postpone a motion', 'Periodic ___'],
    THINK: ['Use your head', 'Ponder', '___ outside the box'],
    TIGER: ['Striped cat', 'Woods of golf', 'Detroit ballplayer'],
    TRAIN: ['Locomotive', 'Work out', 'Gravy ___'],
    TRUST: ['Faith', 'Legal arrangement', 'Brain ___'],
    WATCH: ['Wrist timepiece', 'Observe', 'Night ___'],
    WATER: ['H2O', 'Give the plants a drink', 'Hot ___'],
    WHEEL: ['Car part', 'Big ___', 'Reinvent the ___'],
    WORLD: ['The globe', '___ Series', 'Out of this ___'],
    WRITE: ['Put on paper', 'Author\'s work', '___ home about'],
    YOUNG: ['Not old', 'Neil of rock', 'Forever ___'],

    /* ---- additional common fill ----
       The bundled bank gives most answers exactly one clue, so the in-game
       "Different clue" hint has nothing to switch to for roughly 4 in 5 words
       (it falls back to a live Datamuse lookup instead — see wordsource.js).
       This batch raises the instant-hit rate for ordinary short fill without
       trying to hand-cover the whole ~2,500-word bank, which doesn't scale by
       hand. Spread across the alphabet rather than piled on A/B, since that's
       where the gap actually showed up. */

    // three letters
    ADO: ['Fuss', 'Much ___ About Nothing'],
    AFT: ['Toward the back of a ship', 'Stern direction'],
    BAD: ['Rotten', 'Naughty'],
    BAG: ['Grocery holder', 'Purse'],
    CAB: ['Taxi', 'Truck driver\'s seat'],
    CAP: ['Baseball hat', 'Bottle top'],
    DAD: ['Father', 'Pop'],
    DAM: ['Beaver\'s dwelling', 'Hoover ___'],
    EAT: ['Have a meal', 'Chow down'],
    EBB: ['Tide\'s low point', 'Recede'],
    FAD: ['Passing trend', 'Here-today-gone-tomorrow craze'],
    FAR: ['Distant', 'So ___ so good'],
    GAP: ['Opening', 'Generation ___'],
    GAS: ['Fuel up on', 'Step on the ___'],
    HAS: ['Owns', 'Possesses'],
    HAT: ['Head cover', 'Old ___ (veteran)'],
    ICY: ['Slippery, as roads', 'Cold and unfriendly'],
    ILL: ['Under the weather', 'Sick'],
    JAB: ['Quick punch', 'Vaccine poke'],
    JAR: ['Pickle container', 'Jolt'],
    KEG: ['Party barrel', 'Beer holder'],
    KIN: ['Relatives', 'Next of ___'],
    LAB: ['Science room', 'Retriever breed, briefly'],
    LAD: ['Young fellow', 'Boy, in Britain'],
    MAD: ['Furious', '___ scientist'],
    MAN: ['Adult male', 'Chess piece'],
    NAG: ['Pester', 'Old horse'],
    NAP: ['Quick sleep', 'Afternoon rest'],
    OAF: ['Clumsy person', 'Lout'],
    OAK: ['Sturdy tree', 'Acorn producer'],
    PAD: ['Notepad', 'Launch site'],
    PAL: ['Buddy', 'Chum'],
    RAG: ['Cleaning cloth', 'Tabloid, disparagingly'],
    RAM: ['Force in', 'Male sheep'],
    SAD: ['Blue', 'Tearjerker-inducing'],
    SAG: ['Droop', 'Lose firmness'],
    TAD: ['Small amount', 'Just a bit'],
    TAN: ['Sun-kissed skin', 'Beige'],
    UFO: ['Unexplained sky sighting', 'Flying saucer, for short'],
    UGH: ['Sound of disgust', '"How annoying!"'],
    VAN: ['Moving truck', 'Band\'s tour vehicle'],
    VAT: ['Large tank', 'Brewery container'],
    WAG: ['Tail motion', 'Prankster'],
    WAR: ['Armed conflict', 'Bidding ___'],
    YAM: ['Sweet potato', 'Thanksgiving side'],
    YAP: ['Small dog\'s bark', 'Chatter'],
    ZAP: ['Microwave, briefly', 'Hit with electricity'],
    ZEN: ['Calm state of mind', 'Buddhist practice'],

    // four letters
    SALE: ['Discount period', 'Yard ___', 'Going-out-of-business event'],
    ACRE: ['Land measure', 'Farm unit'],
    AGED: ['Grew old', 'Like fine wine'],
    BABY: ['Infant', 'Coddle'],
    BACK: ['Spine area', 'Support, with "up"'],
    CAFE: ['Coffee shop', 'Bistro'],
    CAGE: ['Bird\'s enclosure', 'Batting practice area'],
    DAME: ['British title', 'Old-fashioned word for woman'],
    DAMP: ['Slightly wet', 'Put a ___er on'],
    EACH: ['Per item', 'Apiece'],
    EARL: ['Nobleman', 'Grey tea namesake'],
    FACT: ['True statement', '___ of life'],
    FADE: ['Gradually disappear', 'Haircut style'],
    GAIN: ['Increase', 'Ill-gotten ___s'],
    GAIT: ['Manner of walking', 'Stride'],
    HAIL: ['Icy precipitation', 'Greet enthusiastically'],
    HAIR: ['Grows on your scalp', 'Split ___s', 'Head of ___'],
    IDOL: ['Object of worship', 'Pop star'],
    INCH: ['Small unit of length', 'Move slowly'],
    JADE: ['Green gemstone', 'Weary and cynical'],
    JAIL: ['Behind bars', 'Slammer'],
    KEEN: ['Sharp, as a mind', 'Eager'],
    KEEP: ['Retain', 'Castle stronghold'],
    LACE: ['Delicate fabric', 'Tie a shoe'],
    LACK: ['Be without', 'Shortage'],
    MADE: ['Constructed', 'Have it ___'],
    MAID: ['Housekeeper', 'Old ___ (unmarried woman)'],
    NAME: ['What you\'re called', 'Reputation'],
    NAPE: ['Back of the neck', 'Where a collar sits'],
    OATH: ['Solemn promise', 'Courtroom vow'],
    OBEY: ['Follow orders', 'Do as told'],
    PACE: ['Walking speed', 'Keep ___ with'],
    PACT: ['Formal agreement', 'Non-aggression ___'],
    QUIT: ['Give up', 'Resign'],
    QUIZ: ['Pop test', 'Trivia game'],
    RACE: ['Speed contest', 'Human ___'],
    RACK: ['Storage frame', 'Pool table need'],
    SAGA: ['Long, dramatic tale', 'Norse epic'],
    SAIL: ['Boat\'s canvas', 'Smooth through'],
    TACK: ['Change direction, at sea', 'Sharp turn'],
    TACO: ['Folded tortilla dish', 'Tuesday special, often'],
    UGLY: ['Not pretty', 'Rear its head'],
    UNDO: ['Reverse an action', 'Ctrl+Z command'],
    VAIN: ['Overly proud', 'In ___ (fruitlessly)'],
    VALE: ['Poetic valley', 'Farewell, in Latin'],
    WADE: ['Walk through shallow water', 'Get in slowly'],
    WAGE: ['Hourly pay', 'Carry out, as war'],
    YARD: ['Backyard', 'Three feet'],
    YAWN: ['Sign of sleepiness', 'Boring thing'],
    ZERO: ['Nothing at all', 'Absolute ___'],
    ZONE: ['Designated area', 'End ___ (touchdown spot)'],

    // five letters
    ABIDE: ['Put up with', 'Live by the rules'],
    ABOUT: ['Approximately', 'Concerning'],
    BACON: ['Breakfast strip', 'Bring home the ___'],
    BADGE: ['Sheriff\'s star', 'Scout\'s award'],
    CABIN: ['Log home', 'Airplane section'],
    CABLE: ['TV service', 'Thick rope'],
    DAILY: ['Every day', 'Newspaper, often'],
    DAIRY: ['Milk products', 'Farm section'],
    EAGER: ['Enthusiastic', 'Chomping at the bit'],
    EARLY: ['Ahead of schedule', 'The ___ bird'],
    FABLE: ['Moral tale', 'Aesop\'s output'],
    FACET: ['Gem\'s cut surface', 'Aspect'],
    GAUGE: ['Measuring tool', 'Estimate'],
    GAUNT: ['Thin and haggard', 'Sunken-cheeked'],
    HABIT: ['Nun\'s garment', 'Recurring routine'],
    HARSH: ['Unforgivingly severe', 'Grating'],
    ICING: ['Cake topping', 'Frosting'],
    IDEAL: ['Perfect example', 'Model'],
    JEANS: ['Denim pants', 'Blue ___'],
    JELLY: ['Toast topper', 'Wobbly dessert'],
    KAYAK: ['Narrow paddled boat', 'Palindrome watercraft'],
    KNACK: ['Special skill', 'Talent for something'],
    LABEL: ['Product tag', 'Record company'],
    LABOR: ['Hard work', 'Childbirth process'],
    MACAW: ['Colorful parrot', 'Tropical bird'],
    MAKER: ['Manufacturer', 'Meet your ___'],
    NAKED: ['Without clothes', 'To the ___ eye'],
    NANNY: ['Child caretaker', 'British grandma'],
    OASIS: ['Desert refuge', 'Welcome relief'],
    OCCUR: ['Take place', 'Come to mind, with "to"'],
    PAINT: ['Wall coating', 'Artist\'s medium'],
    PANEL: ['Discussion group', 'Wall section'],
    QUACK: ['Duck\'s sound', 'Medical fraud'],
    QUAKE: ['Tremble', 'Earthquake, for short'],
    RADAR: ['Detection system', 'Fly under the ___'],
    RADIO: ['Car stereo', 'Broadcast medium'],
    SADLY: ['Unfortunately', 'In a mournful way'],
    SAINT: ['Holy figure', 'New Orleans footballer'],
    TACKY: ['Cheaply gaudy', 'Still sticky'],
    TAFFY: ['Chewy candy', 'Saltwater treat'],
    UNCLE: ['Parent\'s brother', 'Sam of recruiting posters'],
    UNDER: ['Below', 'Go ___ (submit)'],
    VAGUE: ['Not specific', 'Hazy'],
    VALID: ['Legally acceptable', 'Sound, as an argument'],
    WAGER: ['Bet', 'Stake'],
    WAGON: ['Covered pioneer vehicle', 'Little red ___'],
    YACHT: ['Luxury boat', 'Regatta vessel'],
    YEAST: ['Bread-rising agent', 'Brewer\'s ingredient'],
    ZEBRA: ['Striped African animal', 'Referee\'s nickname'],
    ZESTY: ['Full of flavor', 'Citrusy and vibrant'],

    /* ---- highest-frequency words, prioritized ----
       Corpus frequency was ranking pure grammatical connectives (THAT, WHO,
       THAN...) above every real noun in the bank — fixed by excluding those
       from the word list entirely (see wordsource.js's BLOCKED set and the
       stripped bundled files). This batch is what's left once that's fixed:
       the actual highest-frequency words a puzzle will reach for, which
       previously fell through to a single flat dictionary definition each. */

    ONE: ['First number', 'Uno, in English', 'The loneliest number, in song'],
    THERE: ['Not here', 'Wherever that is', '"So ___!" (taunt)'],
    MORE: ['Additional', 'Oliver Twist\'s request', 'Encore shout'],
    OTHER: ['Not this one', 'The remaining one', 'Every ___ day'],
    ALL: ['Every bit', 'Total', '___ or nothing'],
    NEW: ['Fresh', 'Brand ___', 'Year starter'],
    HAVE: ['Possess', 'Own', '___ a nice day'],
    ONLY: ['Sole', 'Solely', 'One and ___'],
    TWO: ['A couple', 'Deuce', 'Tea for ___'],
    SUCH: ['Of that kind', '___ is life', 'No ___ thing'],
    SEE: ['Spot', 'Understand', 'Long time, no ___'],
    FIRST: ['Number one', 'Ahead of the rest', '___-rate'],
    THEN: ['Next', 'Back ___', 'Now and ___'],
    MOST: ['Nearly all', 'Utmost', '___ Valuable Player'],
    SAID: ['Spoke', 'Mentioned', 'Easier ___ than done'],
    MANY: ['Numerous', 'A good ___', 'How ___?'],
    LIKE: ['Similar to', 'Enjoy', 'Instagram tap'],
    VERY: ['Extremely', 'Truly', 'Real McCoy: the ___ thing'],
    AFTER: ['Following', 'In pursuit of', '___ hours'],
    EVEN: ['Level', 'Divisible by two', 'Break ___'],
    NOW: ['At this moment', 'Right ___', 'Any day ___'],
    OVER: ['Finished', 'Above', 'Game ___'],
    WORK: ['Job', 'Function properly', 'Piece of ___ art'],
    USED: ['Secondhand', 'Utilized', '___ to (accustomed)'],
    LIFE: ['Existence', 'Board game', 'Get a ___!'],
    WAY: ['Route', 'Manner', 'No ___!'],
    USE: ['Employ', 'Utilize', 'Make ___ of'],
    MUCH: ['A lot', 'How ___?', 'Too ___ of a good thing'],
    SAME: ['Identical', 'Unchanged', 'One and the ___'],
    WELL: ['Water source', 'Healthy', 'Wishing ___'],
    JUST: ['Fair', 'Merely', '___ kidding'],
    GOOD: ['Not bad', 'Virtuous', '___ grief!'],
    MAKE: ['Create', 'Brand', '___ or break'],
    THREE: ['A trio', 'Strikes, in baseball', 'Musketeers\' count'],
    STATE: ['Condition', 'Texas, e.g.', '___ of the Union'],
    OWN: ['Possess', 'Admit', 'Hold your ___'],
    HERE: ['In this spot', 'Not there', '"___ we go!"'],
    OUT: ['Not in', 'Revealed, as a secret', 'Strike-three result'],
    KNOW: ['Be certain of', 'Recognize', 'You ___ what?'],
    PART: ['Piece', 'Role in a play', 'For the most ___'],
    LONG: ['Lengthy', 'Yearn (for)', '___ shot'],
    GREAT: ['Excellent', 'Grand', '___ Dane'],
    DAY: ['24 hours', 'Sunrise to sunset', '___dream'],
    FOUND: ['Located', 'Established, as a company', 'Lost and ___'],
    STILL: ['Motionless', 'Nevertheless', 'Whiskey maker'],
    TOO: ['Also', 'Excessively', 'Me ___'],
    RIGHT: ['Correct', 'Opposite of left', 'Bill of ___s'],
    HIGH: ['Lofty', 'Stoned', '___ five'],
    CASE: ['Legal matter', 'Container', 'In ___ of emergency'],
    TAKE: ['Grab', 'Movie shoot attempt', '___ it or leave it'],
    MEN: ['Guys', '___ at Work (band)', 'Chess pieces, e.g.'],
    PLACE: ['Location', 'Second, in a race', 'Take ___'],
    OLD: ['Aged', 'Former', '___ school'],
    SMALL: ['Little', 'Talk ___', '___ print'],
    GET: ['Obtain', 'Understand', '___ it?'],
    GIVEN: ['Presented', 'Assumed true', '___ name'],
    COME: ['Approach', 'Arrive', '___ again?'],
    AGAIN: ['Once more', 'Here we go ___', 'Encore!'],
    LARGE: ['Big', 'At ___ (free)', 'Larger than life'],
    POINT: ['Sharp end', 'Purpose', 'Beside the ___'],
    YEAR: ['12 months', 'Annual unit', 'Leap ___'],
    FORM: ['Shape', 'Document to fill out', 'In good ___'],
    GROUP: ['Cluster', 'Band', 'Support ___'],
    LESS: ['Not as much', 'More or ___', 'Couldn\'t care ___'],
    DATA: ['Info', 'Star Trek android', 'Big ___'],
    NEED: ['Require', 'Necessity', '___ to know'],
    PRESS: ['Push', 'Media, collectively', '___ conference'],
    LEFT: ['Not right', 'Departed', 'Two ___ feet'],
    ORDER: ['Restaurant request', 'Sequence', 'Law and ___'],
    SOME: ['A few', 'Unspecified amount', '___ nerve!'],
    HUMAN: ['Person', 'Not animal', '___ nature'],
    CAME: ['Arrived', 'Approached', 'Veni, vidi, vici: I ___'],
    SAY: ['Utter', 'Speak', 'You don\'t ___!'],
    SET: ['Collection', 'TV filming location', 'Ready, ___, go!'],
    STUDY: ['Hit the books', 'Examine closely', 'Case ___'],
    GOD: ['Deity', 'Supreme being', 'Oh my ___!'],
    BEING: ['Creature', 'Existence', 'Human ___'],
    LAST: ['Final', 'Endure', '___ but not least'],
    LAW: ['Legal rule', 'Statute', 'Mother-in-___'],
    FIND: ['Discover', 'Locate', 'Treasure hunt goal'],
    FOUR: ['A quartet', 'Score, less six', 'Fantastic ___'],
    LEVEL: ['Flat', 'Video game stage', 'On the ___'],
    GIVE: ['Donate', 'Yield', '___ and take'],
    YET: ['So far', 'Nonetheless', 'Not ___'],
    WANT: ['Desire', 'Crave', '___ ad'],
    LET: ['Allow', 'Tennis do-over', '___ it be'],
    BOOK: ['Read this', 'Reserve', 'Hit the ___s'],
    BODY: ['Torso', 'Corpse', '___ of water'],
    GOING: ['Departing', 'Underway', 'Comings and ___s'],
    ONCE: ['One time', 'Formerly', '___ upon a time'],
    ABOVE: ['Overhead', 'Superior to', '___ and beyond'],
    VALUE: ['Worth', 'Cherish', 'Face ___'],
    HELP: ['Assist', 'Aid', '___ desk'],
    NEXT: ['Following', 'Then', '___, please!'],
    BEST: ['Top choice', 'Finest', '___ man'],
    AWAY: ['Not present', 'Distant', 'Right ___'],
    KNOWN: ['Familiar', 'Recognized', 'Well-___'],
    PUT: ['Placed', 'Stay ___', '___ up or shut up'],
    BASED: ['Founded, with "on"', 'Located', 'Fact-___'],
    DOWN: ['Not up', 'Feeling blue', 'Touch___'],
    SIDE: ['Team', 'Dish accompaniment', 'Wrong ___ of the bed'],
    HEAD: ['Noggin', 'Boss', '___ over heels'],
    SELF: ['Ego', 'One\'s own person', '___-portrait'],
    TYPE: ['Kind', 'Keyboard action', 'Blood ___'],
    WHITE: ['Snow\'s color', 'Egg part', '___ House'],
    LOOK: ['Glance', 'Appear', '___ before you leap'],
    CHILD: ['Kid', 'Offspring', '___\'s play'],
    TAKEN: ['Occupied, as a seat', 'Captured', 'Smitten, if ___ with'],
    WHOLE: ['Entire', 'Complete', '___ nine yards'],
    JOHN: ['Elton or Lennon', 'Toilet, slangily', 'Dear ___ letter'],
    LEAST: ['Smallest amount', 'Fewest', 'Last but not ___'],
    LOVE: ['Adore', 'Tennis zero', '___ at first sight'],
    LOCAL: ['Nearby', 'Neighborhood-bar regular', 'Not express, as a train'],
    VIEW: ['Vista', 'Opinion', 'Point of ___'],
    FIVE: ['High ___', 'Half of ten', 'Jackson ___'],
    FIG: ['Fruit in a Newton', 'Wrinkly purple fruit', 'Don\'t give a ___'],
    MAJOR: ['Significant', 'Army rank', 'College focus'],
    MIND: ['Brain', 'Object (to)', '___ over matter'],
    LAND: ['Earth\'s surface', 'Touch down', 'Promised ___'],
    FREE: ['No charge', 'Liberated', 'Duty-___'],
    DONE: ['Finished', 'Well-___ steak', 'Over and ___ with'],
    LOW: ['Not high', 'Cow\'s sound', '___ blow'],
    SENSE: ['Common ___', 'Perceive', 'Sixth ___'],
    DEATH: ['End of life', 'Grim Reaper\'s business', '___ and taxes'],
    TRUE: ['Accurate', 'Loyal', '___ or false'],
    RATE: ['Speed', 'Interest ___', 'At any ___'],
    CLASS: ['Course', 'Elegance', 'First ___'],
    MODEL: ['Runway walker', 'Small-scale replica', 'Role ___'],
    BLACK: ['Coal\'s color', 'Coffee order', '___ sheep'],
    ROOM: ['Space', 'Bedroom, e.g.', '___ for improvement'],
    GOT: ['Obtained', 'Understood', '___ milk?'],
    ACT: ['Play segment', 'Perform', 'Balancing ___'],
    CARE: ['Concern', 'Tend to', 'Take ___!'],
    ALONG: ['Beside', 'Onward', 'Come ___'],
    ROLE: ['Part in a play', 'Function', '___ model'],
    REAL: ['Genuine', 'Actual', 'Get ___'],
    BEGAN: ['Started', 'Commenced', 'It all ___ with'],
    FULL: ['Not hungry', 'Complete', '___ moon'],
    TOTAL: ['Sum', 'Complete', 'Wreck a car, e.g.'],
    SHOW: ['TV program', 'Reveal', '___ and tell'],
    SOUTH: ['Opposite of north', 'Down under, loosely', '___ Pole'],
    WORD: ['Vocabulary unit', 'Promise', '___ on the street'],
    QUITE: ['Rather', 'Very', 'Not ___'],
    SHORT: ['Not tall', 'Brief', 'Come up ___'],
    KIND: ['Type', 'Compassionate', 'Two of a ___'],
    HALF: ['50 percent', 'Basketball period', 'Better ___'],
    THING: ['Object', 'Do your own ___', 'Not a ___'],
    SAW: ['Cutting tool', 'Observed', 'Old ___ (proverb)'],
    WOMAN: ['Female adult', 'Lady', '___ of the house'],
    TELL: ['Reveal', 'Narrate', '___ me about it'],
    NORTH: ['Opposite of south', '___ Pole', 'True ___'],
    THIRD: ['Bronze-medal position', 'Baseball base', '___ wheel'],
    CLEAR: ['Transparent', 'Obvious', '___ the air'],
    FELT: ['Sensed', 'Fabric for crafts', 'Never ___ better'],
    TERM: ['Word', 'School period', 'In ___s of'],
    KNEW: ['Was aware', 'Recognized', 'I ___ it!'],
    FORCE: ['Push', 'Star Wars power', 'Air ___'],
    BLOOD: ['Vital fluid', 'Kin, as in ___ relative', '___, sweat, and tears'],
    PAST: ['Bygone era', 'Beyond', 'Living in the ___'],
    MEAN: ['Cruel', 'Average', 'What do you ___?'],
    SINCE: ['From then until now', 'Because', '___ when?'],
    DUE: ['Expected', 'Owed', '___ date'],
    FOOD: ['Sustenance', 'Meal', '___ for thought'],
    CAUSE: ['Reason', 'Bring about', 'Just ___'],
    TEST: ['Exam', 'Trial', 'Put to the ___'],
    READ: ['Peruse', 'Interpret', 'Well-___'],
    MAIN: ['Primary', 'Water pipe', '___ course'],
    GAVE: ['Donated', 'Handed over', '___ up'],
    COURT: ['Tennis venue', 'Woo', 'Supreme ___'],
    SOON: ['Shortly', 'Before long', 'See you ___'],
    FEEL: ['Sense', 'Touch', '___ the burn'],
    STORY: ['Tale', 'Building level', 'Sob ___'],
    CLOSE: ['Shut', 'Near', '___ call'],
    TRADE: ['Exchange', 'Profession', '___ secret'],
    WEST: ['Opposite of east', 'Mae ___', 'Go ___, young man'],
    CALL: ['Phone', 'Decision', '___ it a day'],
    TURN: ['Rotate', 'Chance in a game', '___ the tables'],
    COST: ['Price', 'Toll', 'At all ___s'],
    NEAR: ['Close by', 'Almost', '___ miss'],
    PLAY: ['Theater production', 'Have fun', '___ it by ear'],
    SIZE: ['Dimensions', 'One-___-fits-all', 'Cut down to ___'],
    SIX: ['Half a dozen', 'Deep ___', 'Sweet ___teen'],
    HARD: ['Difficult', 'Rock ___', '___ hat'],
    CELL: ['Prison room', 'Phone', 'Basic life unit'],
    LATE: ['Tardy', 'Deceased', 'Better ___ than never'],
    RANGE: ['Mountain chain', 'Stove', 'Free ___'],
    SURE: ['Certain', '"For ___!"', 'Make ___'],
    PLAN: ['Blueprint', 'Scheme', 'Floor ___'],
    BASIC: ['Elementary', 'Unremarkable, slangily', '___ instinct'],
    BELOW: ['Beneath', 'Under', 'The undersigned, ___'],
    UNTIL: ['Till', 'Up to the point that', '___ death do us part'],
    BASIS: ['Foundation', 'Grounds', 'On a daily ___'],
    SON: ['Male offspring', 'Prodigal ___', '___ of a gun'],
    TODAY: ['This day', 'Right now', '___ show'],
    POOR: ['Not rich', 'Pitiable', '___ excuse'],
    EAST: ['Opposite of west', 'Sunrise direction', '___ Coast'],
    LIVE: ['Alive', 'Reside', 'Broadcast ___'],
    ALONE: ['By oneself', 'Solo', 'Home ___'],
    LOST: ['Misplaced', 'Defeated', 'Get ___!'],
    HEARD: ['Perceived by ear', 'Listened to', 'Never ___ of it'],
    DOING: ['Performing', 'How are you ___?', 'Up to no good, e.g.'],
    RED: ['Stop-sign color', 'Communist', 'Caught ___-handed'],
    MAY: ['Spring month', 'Might', '___ I help you?'],
    OFF: ['Not on', 'Day ___', 'Gone bad, as milk'],
    FRONT: ['Face forward', 'Weather system', 'Put up a ___'],
    UNION: ['Labor group', 'Marriage', '___ Jack'],
    JOB: ['Occupation', 'Task', 'Day ___'],
    BIG: ['Large', 'Important', '___ Apple'],
    YES: ['Affirmative', '"Absolutely!"', '___ man'],
    DIE: ['Perish', 'Dice, singular', 'Do or ___'],
    VOICE: ['Speaking sound', 'Opinion', 'The ___ (TV show)'],
    WIFE: ['Spouse', 'Better half', 'Trophy ___'],
    LEAVE: ['Depart', 'Vacation time', '___ no trace'],
    PRICE: ['Cost', 'Tag amount', 'The ___ Is Right'],
    REST: ['Relax', 'Remainder', '___ in peace'],
    MARCH: ['Third month', 'Parade', '___ Madness'],
    ISSUE: ['Problem', 'Magazine edition', 'At ___'],
    LORD: ['British nobleman', 'Deity, with "the"', '___ of the Rings'],
    TOWN: ['Small city', 'Talk of the ___', 'Ghost ___'],
    CENT: ['Penny', '1/100 of a dollar', 'Not worth a red ___'],

    /* ---- dictionary-accuracy fixes ----
       Found by scanning 400 actually-generated puzzles for suspiciously
       long/comma-heavy/digit-containing clue text, then checking what
       Datamuse had actually surfaced. It wasn't just badly worded — some of
       these were flatly the wrong sense: TUNA came back as Māori mythology
       ("son of Manga-wai-roa and source of eels"), TEN as "an inexact
       quantity...between 20 and 100", AMAZE as "to fill with panic" (an
       archaic sense, not what the word means today), CRANE as "a siphon...for
       drawing liquors out of a cask". Datamuse doesn't guarantee its first
       definition is the common one; these override it with the sense anyone
       would actually recognize. */

    AGENT: ['Secret ___', 'Real estate ___', 'Double ___'],
    WED: ['Marry', 'Say "I do"', 'Tie the knot'],
    LEAN: ['Skinny', 'Rely (on)', '___ Cuisine'],
    HUGE: ['Enormous', 'Gigantic', 'Ginormous'],
    RIVAL: ['Competitor', 'Nemesis', 'Arch-___'],
    EDEMA: ['Swelling from fluid buildup', 'Puffy-ankles symptom', 'Medical bloating'],
    HIRE: ['Employ', 'Bring on board', 'Rent, in Britain'],
    ANTE: ['Poker buy-in', 'Up the ___', 'Pre-bet chip pile'],
    ALTO: ['Choir voice', 'Sax type', 'Between tenor and soprano'],
    GALE: ['Strong wind', 'Storm force', 'Force 8, on the Beaufort scale'],
    DEBIT: ['Bank statement column', 'Opposite of credit', 'Account deduction'],
    LAVA: ['Molten rock', 'Volcano flow', '___ lamp'],
    ATLAS: ['Book of maps', 'Neck vertebra', 'Greek Titan who held up the sky'],
    SHAKE: ['Milkshake', 'Tremble', '___ a leg'],
    SEVEN: ['Lucky number', 'Days in a week', '___ deadly sins'],
    BOOST: ['Give a lift', 'Confidence ___', 'Turbocharger\'s push'],
    GEN: ['Info, briefly', 'Generation, for short', '___ Z'],
    LASH: ['Eyelash', 'Whip stroke', 'Back___'],
    SHAVE: ['Remove facial hair', 'Trim closely', 'Close ___'],
    ALTAR: ['Wedding spot', 'Church platform', 'Sacrificial table'],
    SLATE: ['Roofing material', 'Chalkboard, once', 'Clean ___'],
    STAKE: ['Wager', 'Tent peg', 'Vampire hunter\'s tool'],
    APRON: ['Kitchen garment', 'Chef\'s cover-up', 'Stage-front area'],
    CRANE: ['Long-necked bird', 'Construction lifter', 'Stretch, as one\'s neck'],
    TRIO: ['Threesome', 'Band of three', 'Musical group of three'],
    RIPE: ['Ready to eat, as fruit', 'Mature', '___ old age'],
    APART: ['Separated', 'Not together', 'Come ___'],
    STOW: ['Pack away', 'Store securely', '___ away'],
    TREK: ['Long journey', 'Hike', 'Star ___'],
    PULSE: ['Heartbeat', 'Take one\'s ___', 'Lentils and beans, collectively'],
    ERASE: ['Delete', 'Wipe clean', '___ history'],
    SHOE: ['Footwear', 'Horse\'s need', 'If the ___ fits'],
    MASON: ['Bricklayer', 'Secret-society member', '___ jar'],
    NERVE: ['Gutsy boldness', 'Body signal-carrier', 'Get on someone\'s ___s'],
    OBOE: ['Reed instrument', 'Orchestra tuner', 'Double-reed woodwind'],
    DIP: ['Chip companion', 'Quick swim', 'Dance move'],
    TUNA: ['Canned fish', 'Sushi staple', 'Charlie the ___ (mascot)'],
    TARDY: ['Late', 'Behind schedule', 'Not on time'],
    WIRE: ['Metal thread', 'Telegram, once', 'Down to the ___'],
    INDEX: ['Book\'s back-page guide', 'Pointer finger', 'Stock market gauge'],
    PAY: ['Compensate', 'Salary', '___ attention'],
    ARROW: ['Cupid\'s ammo', 'Direction indicator', 'Straight as an ___'],
    LEG: ['Body limb', 'Table support', 'Pull someone\'s ___'],
    GEAR: ['Equipment', 'Bike setting', 'Shift ___s'],
    DROVE: ['Herded animals', 'Operated a car', 'Cattle group'],
    NEST: ['Bird\'s home', 'Cozy hideaway', 'Empty ___er'],
    WEED: ['Garden pest', 'Marijuana, slangily', '___ out'],
    SHED: ['Garden structure', 'Lose, as fur', 'Tool ___'],
    ALARM: ['Wake-up device', 'Warning', 'False ___'],
    TEE: ['Golf starting point', 'T-shirt, for short', '___ off'],
    PEEL: ['Banana\'s skin', 'Remove skin', 'Eye ___'],
    SCENE: ['Movie segment', 'Dramatic outburst', 'Behind the ___s'],
    OTTER: ['River mammal', 'Sea ___ (kelp dweller)', 'Holds hands with others while sleeping'],
    RUSH: ['Hurry', 'Fraternity recruitment', 'Adrenaline ___'],
    SCORE: ['Final tally', 'Movie music', 'Know the ___'],
    USUAL: ['The norm', 'Regular order at a bar', 'Business as ___'],
    MESS: ['Disorderly state', 'Military dining hall', '___ hall'],
    RENEW: ['Extend, as a library book', 'Refresh', '___ a subscription'],
    REALM: ['Kingdom', 'Domain', 'Animal ___'],
    TEN: ['Half of twenty', 'Bowling pin count', 'Perfect score'],
    AMAZE: ['Astonish', 'Wow', 'Blow (someone\'s) mind'],
    ARMED: ['Carrying a weapon', 'Ready for battle', 'Locked and loaded'],
    LEGAL: ['Permitted by law', 'Lawful', '___ pad'],
    ORAL: ['Spoken', 'Relating to the mouth', 'Not written, as an exam'],
    SPAR: ['Practice-fight', 'Boxing warm-up', 'Verbal ___ring match'],
    SPARE: ['Extra', 'Bowling feat', '___ tire'],
    NASAL: ['Relating to the nose', 'Stuffy-sounding', 'Twangy voice quality'],
    GEL: ['Hair product', 'Set, as Jell-O', 'Come together, as a plan'],
    ETHER: ['Old-time anesthetic', 'The upper sky, poetically', 'Airwaves, as in "the ___"'],
    LOUD: ['Not quiet', 'Garish, as colors', 'Out ___'],
    ROGUE: ['Scoundrel', 'Villain with charm', '___ wave'],
    MAIL: ['Postal delivery', 'Chain ___ (armor)', 'You\'ve got ___'],
    RUSE: ['Trick', 'Ploy', 'Clever deception'],
    SCAB: ['Wound covering', 'Strikebreaker, disparagingly', 'Pick at a ___'],
    TREAT: ['Candy', 'Handle, as a patient', 'Trick or ___'],
    DELAY: ['Postpone', 'Flight holdup', 'Not on time']
  };
})(window);
