/* The Mini — curated crossword clues.

   The generator's default clues come from dictionary definitions (bundled
   lists, or a Datamuse harvest). Those are accurate but read like a glossary:
   "Strong wind", "Spoken", "Card type". Real crossword clues misdirect, use
   fill-in-the-blank, lean on proper nouns and idiom, and vary in register.

   This file overrides the definition for answers that show up often, which is
   where the difference is felt most — the crosswordese that would otherwise
   be clued most blandly. Anything not listed here still falls back to the
   dictionary definition, so partial coverage degrades gracefully.

   Format: ANSWER: [clue, clue, ...]. One is chosen at random per puzzle (the
   Impossible difficulty deliberately takes the last, so put the most oblique
   clue last). Keep them short — the clue bar is one line on mobile. */
(function (global) {
  'use strict';

  global.CURATED_CLUES = {
    /* ---- the classic crosswordese ---- */
    OREO: ['Cookie that\'s often twisted', 'Sandwich in a lunchbox', 'Double Stuf snack'],
    AREA: ['Length times width', 'Neighborhood', 'Rug spec'],
    ERIE: ['Great Lake bordering Ohio', 'Canal of song', 'Pennsylvania port city'],
    IDEA: ['Lightbulb moment', 'Brainstorm result', 'What a bulb signifies'],
    ALOE: ['Sunburn soother', 'Vera\'s plant?', 'Gel-yielding succulent'],
    IRON: ['Golf club or laundry tool', 'Pumping ___', 'Element 26'],
    ECHO: ['Canyon comeback', 'Smart speaker name', 'Repeat offender?'],
    OPEN: ['Not shut', 'Tennis tournament type', 'Ready for business'],
    EASE: ['Lack of difficulty', 'Relieve', 'Put at ___'],
    ERAS: ['Taylor Swift tour name', 'Jurassic and Victorian, e.g.', 'Long stretches'],

    /* ---- three letters ---- */
    ACE: ['Nail the test', 'Top card', 'Serve that can\'t be returned'],
    ADD: ['Do some sums', 'Toss in', 'Opposite of subtract'],
    AGE: ['Get older', 'Number on a cake', 'Bronze or Ice, e.g.'],
    AIR: ['What a tire loses', 'Broadcast', 'Guitar prefix?'],
    ANT: ['Picnic pest', 'Colony member', 'Marvel\'s ___-Man'],
    APE: ['Copy', 'Kong, for one', 'Go ___ (freak out)'],
    ARM: ['Limb with an elbow', 'Chair part', 'Supply with weapons'],
    ART: ['Museum filler', 'The ___ of the Deal', 'Gallery display'],
    ATE: ['Had a bite', 'Consumed', 'Was fed up?'],
    BAT: ['Cave dweller', 'Slugger\'s stick', 'Take a turn at the plate'],
    BEE: ['Spelling contest', 'Hive dweller', 'Busy as a ___'],
    BOX: ['Ring contest', 'Cardboard container', 'Think outside the ___'],
    CAT: ['Nine-lived pet', 'Curiosity victim', 'Jazz fan, once'],
    COW: ['Milk source', 'Have a ___ (freak out)', 'Intimidate'],
    DOG: ['Best friend, they say', 'Hot ___', 'Follow closely'],
    EAR: ['Corn unit', 'It has a drum', 'Lend an ___'],
    EGG: ['Breakfast staple', 'Nest item', '___ on (encourage)'],
    END: ['Finish', 'Football position', 'Means to an ___'],
    EYE: ['Storm center', 'Needle hole', 'Keep an ___ on'],
    FAN: ['Cooling device', 'Devotee', 'Stadium filler'],
    FIT: ['Tantrum', 'In shape', 'Suitable'],
    FLY: ['Soup intruder', 'Travel by air', 'Zipper, on trousers'],
    ICE: ['Rink surface', 'Cubes in a glass', 'Seal the deal, slangily'],
    INK: ['Pen filler', 'Tattoo, informally', 'Sign a deal'],
    JAM: ['Toast topping', 'Traffic snarl', 'Play music loosely'],
    KEY: ['Piano part', 'It opens doors', 'Florida ___ lime'],
    LAP: ['Track circuit', 'Sit on Santa\'s ___', 'Drink like a cat'],
    NET: ['Tennis divider', 'After deductions', 'Catch'],
    OAR: ['Rowboat mover', 'Crew tool', 'Put your ___ in'],
    OWL: ['Night bird', 'Wise one, proverbially', 'Hooter'],
    PEN: ['Writing tool', 'Pig\'s home', 'Mightier than the sword'],
    PIE: ['Easy as ___', 'Chart type', 'Bakery buy'],
    RAT: ['Squealer', 'Lab animal', 'Smell a ___'],
    RUN: ['Jog', 'Stocking flaw', 'Baseball score'],
    SEA: ['Ocean', 'All at ___ (confused)', 'Dead or Red'],
    SKY: ['The limit, they say', 'Blue expanse', 'Where clouds live'],
    SUN: ['Star of our system', 'Beach draw', 'It rises in the east'],
    TEA: ['Cuppa', 'Boston Harbor cargo, once', 'Spill the ___ (gossip)'],
    TIE: ['Neckwear', 'Deadlocked score', 'Bind'],
    TOE: ['Foot digit', '___ the line', 'Sock coverer'],
    TOP: ['Spinning toy', 'Best', 'Shirt, e.g.'],
    WEB: ['Spider\'s work', 'The World Wide ___', 'Network'],
    ZIP: ['Nothing at all', 'Code before an address', 'Fastener'],

    /* ---- four letters ---- */
    ABLE: ['Capable', 'Ready, willing, and ___', 'Cain\'s brother, nearly'],
    ACHE: ['Dull pain', 'Long (for)', 'Head or heart follower'],
    ACID: ['Base opposite', 'Battery liquid', 'Sharp, as wit'],
    ALSO: ['Too', 'In addition', 'Besides'],
    ATOM: ['Tiny bit', 'Splittable thing', 'Element unit'],
    AUTO: ['Car', 'Prefix with pilot', 'Detroit product'],
    BAKE: ['Use the oven', 'Half-___ idea', 'Make cookies'],
    BEAM: ['Grin widely', 'Structural support', 'Ray of light'],
    BELL: ['Ringer', 'Taco ___', 'Saved by the ___'],
    BIRD: ['Early one gets the worm', 'Badminton shuttlecock', 'Larry of the Celtics'],
    BLUE: ['Feeling down', 'Sky color', 'Out of the ___'],
    BOLD: ['Daring', 'Text style', 'Fortune favors the ___'],
    CALM: ['Serene', '___ before the storm', 'Settle down'],
    CARD: ['Deck member', 'Birthday mailing', 'Funny person'],
    CHIP: ['Poker token', 'Salsa scooper', '___ on one\'s shoulder'],
    CITY: ['Urban area', 'Kansas ___', 'Metropolis'],
    COLD: ['Winter feeling', 'Sniffles cause', 'Out ___ (unconscious)'],
    DEAL: ['Bargain', 'Distribute cards', 'Big ___!'],
    DESK: ['Office furniture', 'Where papers pile up', 'Front ___ clerk'],
    DOOR: ['Entryway', 'Next ___ neighbor', 'It may be revolving'],
    EDGE: ['Border', 'Slight advantage', 'On ___ (nervous)'],
    FACE: ['Clock front', 'Confront', 'Poker ___'],
    FIRE: ['Campfire', 'Let go from a job', 'Under ___'],
    FISH: ['Angler\'s catch', 'Aquarium resident', 'Search awkwardly'],
    GAME: ['Match', 'Willing', 'Board or video'],
    GATE: ['Airport waiting spot', 'Fence opening', 'Golden ___ Bridge'],
    GOLD: ['Olympic prize', 'Element 79', 'Heart of ___'],
    HAND: ['Cards you\'re dealt', 'Clock pointer', 'Give a ___'],
    HOME: ['Where the heart is', 'Baseball plate', 'House'],
    IDLE: ['Doing nothing', 'Monty Python\'s Eric', 'Engine state'],
    JAZZ: ['New Orleans music', 'Utah team', 'Liven (up)'],
    KING: ['Chess piece', 'Elvis, with "the"', 'Martin Luther ___ Jr.'],
    LAKE: ['Erie or Tahoe', 'Body of water', 'Salt ___ City'],
    LEAF: ['Autumn faller', 'Book page', 'Turn over a new ___'],
    LINE: ['Queue', 'Drop me a ___', 'Fishing cord'],
    MOON: ['Night light', 'Over the ___', 'Apollo destination'],
    NOTE: ['Musical unit', 'Brief message', 'Take ___ of'],
    OPEN: ['Not closed', 'Golf major', 'Unlock'],
    PARK: ['Central ___', 'Leave the car', 'Ball ___'],
    RAIN: ['Umbrella opener', '___ check', 'Wet weather'],
    RIDE: ['Amusement park attraction', 'Lift', 'Along for the ___'],
    ROAD: ['Highway', 'Hit the ___', 'Abbey ___'],
    ROCK: ['Genre of music', 'Stone', 'Sway back and forth'],
    SALT: ['Pepper\'s partner', 'Sea seasoning', 'Worth one\'s ___'],
    SNOW: ['Winter white stuff', 'Jon of Winterfell', 'Blizzard output'],
    STAR: ['Celebrity', 'Twinkler', 'Rate five ___s'],
    TIME: ['Clock reading', 'Magazine name', '___ flies'],
    WAVE: ['Ocean roller', 'Greeting gesture', 'Stadium crowd move'],
    WIND: ['Breeze', 'Coil up', 'Second ___'],
    WOOD: ['Fireplace fuel', 'Golf club type', 'Can\'t see the forest for the ___s'],

    /* ---- five letters ---- */
    ADAPT: ['Adjust', 'Turn a book into a film', 'Evolve to fit'],
    ADMIT: ['Confess', 'Let in', 'Own up'],
    ALERT: ['On guard', 'Amber ___', 'Warning'],
    ALIVE: ['Kicking', 'Not dead', 'Look ___!'],
    ANGEL: ['Winged helper', 'Investor in a startup', 'Los ___es'],
    APPLE: ['Teacher\'s gift', 'Big ___ (NYC)', 'Newton\'s falling fruit'],
    BEACH: ['Sandy shore', 'Boys of song', 'Where waves land'],
    BEGIN: ['Start', 'Commence', 'Opposite of end'],
    BRAVE: ['Courageous', 'Atlanta ballplayer', 'Face down'],
    BREAD: ['Loaf', 'Money, slangily', 'Bakery staple'],
    BRIEF: ['Short', 'Lawyer\'s filing', 'Fill in quickly'],
    CHAIR: ['Seat', 'Committee head', 'Musical ___s'],
    CLEAN: ['Spotless', 'Come ___ (confess)', 'Tidy up'],
    CLOUD: ['Sky puffball', 'Where data lives now', 'On ___ nine'],
    DANCE: ['Move to music', 'Prom activity', 'Last ___'],
    DREAM: ['Sleep vision', 'Aspiration', 'Field of ___s'],
    EARTH: ['Third rock from the sun', 'Soil', 'Down to ___'],
    ENTER: ['Go in', 'Keyboard key', 'Sign up for'],
    EQUAL: ['The same', 'Sweetener brand', 'All men are created ___'],
    FIELD: ['Baseball setting', 'Area of study', 'Left ___'],
    FLAME: ['Candle top', 'Old ___ (former love)', 'Fire part'],
    FRESH: ['Just picked', 'Sassy', '___ start'],
    FRUIT: ['Apple or pear', 'Labor\'s reward', 'Forbidden ___'],
    GHOST: ['Halloween figure', 'Stop replying, in dating', 'Casper, e.g.'],
    GRAND: ['Impressive', 'Thousand bucks', 'Piano type'],
    GREEN: ['Kermit\'s color', 'Golf target', 'Eco-friendly'],
    HAPPY: ['Glad', 'Dwarf with a grin', '___ hour'],
    HEART: ['Valentine shape', 'Card suit', 'Take it to ___'],
    HOUSE: ['Dwelling', 'Congress chamber', 'Full ___'],
    LAUGH: ['Chuckle', 'Response to a joke', 'Last ___'],
    LEARN: ['Pick up knowledge', 'Study result', 'Live and ___'],
    LEMON: ['Sour citrus', 'Bad car', 'When life gives you ___s'],
    LIGHT: ['Not heavy', 'Bulb output', 'See the ___'],
    LUCKY: ['Fortunate', '___ strike', 'Charm-worthy'],
    MAGIC: ['Sorcery', 'Orlando team', 'Johnson of the Lakers'],
    MONEY: ['Cash', 'Where your mouth is', 'Root of all evil, they say'],
    MUSIC: ['Face the ___', 'Radio output', 'Notes in sequence'],
    NIGHT: ['Day\'s opposite', 'Opening ___', 'Good ___'],
    OCEAN: ['Pacific or Atlantic', 'Frank of R&B', 'Vast blue'],
    PAPER: ['Rock beats it', 'Newspaper', 'Term ___'],
    PARTY: ['Celebration', 'Political group', 'Third ___'],
    PEACE: ['War\'s opposite', 'Nobel category', '___ of mind, nearly'],
    PHONE: ['Pocket device', 'Ring giver', '___ a friend'],
    PIANO: ['88-key instrument', 'Softly, in music', 'Grand or upright'],
    PLANT: ['Factory', 'Put in soil', 'Leafy thing'],
    POWER: ['Electricity', 'Strength', '___ nap'],
    QUICK: ['Fast', 'Cut to the ___', '___ study'],
    RIVER: ['Nile or Amazon', 'Poker\'s last card', 'It has banks'],
    ROBOT: ['Mechanical worker', 'Sci-fi staple', 'Dance style'],
    SHARP: ['Keen', 'Musical symbol', 'At 3 o\'clock ___'],
    SHORE: ['Coastline', 'Jersey ___', 'Prop (up)'],
    SMILE: ['Say cheese', 'Grin', 'Turn that frown around'],
    SNAKE: ['Slithering reptile', 'Plumber\'s tool', 'Treacherous person'],
    SOUND: ['Noise', 'Puget ___', 'Sensible'],
    SPACE: ['Final frontier', 'Room', 'Bar on a keyboard'],
    SPEED: ['Velocity', 'Keanu film', '___ bump'],
    STAGE: ['Theater platform', 'Phase', 'Set the ___'],
    STONE: ['Rock', 'Rolling ___', 'Kidney ___'],
    STORM: ['Bad weather', 'Take by ___', 'Brainstorm, briefly'],
    SUGAR: ['Sweetener', 'Term of endearment', 'Brown or white'],
    SWEET: ['Sugary', 'Home ___ home', 'Kind'],
    TABLE: ['Dining furniture', 'Postpone a motion', 'Periodic ___'],
    THINK: ['Use your head', 'Ponder', '___ outside the box'],
    TIGER: ['Striped cat', 'Woods of golf', 'Detroit ballplayer'],
    TRAIN: ['Locomotive', 'Work out', 'Gravy ___'],
    TRUST: ['Faith', 'Legal arrangement', 'Brain ___'],
    WATCH: ['Wrist timepiece', 'Observe', 'Night ___'],
    WATER: ['H2O', 'Give the plants a drink', 'Hot ___'],
    WHEEL: ['Car part', 'Big ___', 'Reinvent the ___'],
    WORLD: ['The globe', '___ Series', 'Out of this ___'],
    WRITE: ['Put on paper', 'Author\'s work', '___ home about'],
    YOUNG: ['Not old', 'Neil of rock', 'Forever ___']
  };
})(window);
